export const list = [
   
    {firstName: 'Brian',
    lastName: 'Vaughn',
     email: 'random',
     phoneNumber: '336-555-5555', 
     developerType: 'web',
     education: 'High School', 
     relocate: 'yes', 
     question: '', 
     Resumé: 'file'},
     {firstName: 'Brian',
     lastName: 'Vaughn',
      email: 'random',
      phoneNumber: '336-555-5555', 
      developerType: 'web',
      education: 'High School', 
      relocate: 'yes', 
      question: '', 
      Resumé: 'file'},
      {firstName: 'Brian',
      lastName: 'Vaughn',
       email: 'random',
       phoneNumber: '336-555-5555', 
       developerType: 'web',
       education: 'High School', 
       relocate: 'yes', 
       question: '', 
       Resumé: 'file'},
       {firstName: 'Brian',
       lastName: 'Vaughn',
        email: 'random',
        phoneNumber: '336-555-5555', 
        developerType: 'web',
        education: 'High School', 
        relocate: 'yes', 
        question: '', 
        Resumé: 'file'},


  
];